### PR TITLE
Disable default-features on rand dependency to avoid std version

### LINKED ISSUE #105: New cortex-m-rt rand dependency breaks builds
I was just trying to port the `microbit` crate to `cortex-m-rt` 0.6.0 but I'm facing this here:
```
   Compiling rand_core v0.2.1
   Compiling cortex-m-rt v0.6.0
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv6m-none-eabi` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `rand_core`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

@japaric Seems something is messing (or not) with the required flags for `no_std`.

### PR DESCRIPTION
**Pull request by therealprof**
Due to the single dependency tree, the attempted use of a std version
flips all depending crates to the std version as well which will not
compile on no_std systems.

Fixes #105

Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by japaric** [comment]
LGTM. Could you add an example that links to rand with default features disabled? That should serve as a regression test.

**Comment by japaric** [comment]
note that to get the example to build on CI you'll have to add it: https://github.com/rust-embedded/cortex-m-rt/blob/5baa082ff147a3b90fa00d09de488490be8b5e93/ci/script.sh#L14-L28

**Comment by therealprof** [comment]
Shouldn't any example do? The rand stuff is used for generation of unique linker symbols, no?

**Comment by therealprof** [comment]
@japaric Please have a look now.

**Comment by japaric** [comment]
Hmm, the build is failing since the first commit with: "error[E0658]: use of unstable library feature 'rustc_private'", and I don't understand why ...

**Comment by therealprof** [comment]
😀. And now travis-ci is running into the exact same problem I mentioned in the ticket before...

**Comment by therealprof** [comment]
I think it's because the version seems to be newer than the upstream version so it uses that instead which triggers this problem. As I said: I'm having the same troubles locally.

**Comment by therealprof** [comment]
I simply compiled the example via `cargo build --example rand`. Worked without problems.

**Comment by therealprof** [comment]
LOL and of course once I fixed the type it does not compile anymore. 😀

Raining lemons today...

**Comment by japaric** [comment]
@therealprof you didn't add `#![feature(rustc_private)]` to `macros/src/lib.rs` right? That would "fix" the problem by making the crate using the `rand` shipped with the toolchain but we can't use that because it's unstable.

**Comment by therealprof** [comment]
That's indeed what I did. Do you want me to rewrite the rand stuff in macros to use the seedable rng which works in no_std?

**Comment by japaric** [comment]
> Do you want me to rewrite the rand stuff in macros to use the seedable rng which works in no_std?

Yes, please. Though, I'm concerned that using a seed which is not randomly generated will result in (a) predictable identifiers which then the user can the use to call exception handlers breaking the non-reentrant invariant, and / or (b) collisions between `#[entry] fn foo() -> ! { .. }` and `#[pre_init] unsafe fn foo() {}` if the seed is derived from the identifier.

**Comment by therealprof** [comment]
@japaric Well, the stuff is not really cryptographic anyway. If someone wants to desperately do bad stuff with the entry points, they can still do it. Collisions would be indeed a problem but a `rand::SeedableRng` is not going to have more of a collision than the threaded rng. We could use `mem::uninitialized()` to see the RNG, that would make it slightly more unpredictable, if you're worried about reusing the same seed over and over again.

**Comment by japaric** [comment]
> If someone wants to desperately do bad stuff with the entry points, they can still do it.

They can't with the current implementation.

If they call `cargo expand` and see that `entry` was renamed to `bsb49kvt39ff0w29` and then modify their code to call `bsb49kvt39ff0w29` it won't compile next time because the attribute will generate a *different* identifier. The key property here is that the attribute produces a different identifier on each run. It's not important what RNG is used; it's important that the *seed* of the RNG is different on *each run*.

> We could use mem::uninitialized() to seed the RNG

That could turn into UB in any future LLVM release so it's not an option.

**Comment by adamgreig** [comment]
Can we just prevent the function from being called from safe code? I get that we can't just hide it in a private module (sadly, as that seems like it would totally fix the issue) but perhaps we can stick it inside an unsafe function wrapper with a predictable name? Or any other options to avoid rand?

Otherwise... seed with the build time... :smiling_imp:

**Comment by therealprof** [comment]
> If they call cargo expand and see that entry was renamed to bsb49kvt39ff0w29 and then modify their code to call bsb49kvt39ff0w29 it won't compile next time because the attribute will generate a different identifier. 

Sure... but then again if someone *really* wants to do it they can do still it after the fact, i.e. without recompiling from source.

> it's important that the seed of the RNG is different on each run.

Well, it's a new feature anyway. 😏

> That could turn into UB in any future LLVM release so it's not an option.

Uhm....

> Otherwise... seed with the build time... 😈

Or address of something in the running process. ;)

**Comment by japaric** [comment]
> perhaps we can stick it inside an unsafe function wrapper with a predictable name?

That's an option but we would need a trampoline to preserve the safety that the user declared:

```
#[exception]
fn SysTick() { .. }

// expands into
#[no_mangle]
pub unsafe fn SysTic() {
    // copy paste the user function here
    fn SysTick() { .. }

    SysTick()
}
```

> Otherwise... seed with the build time... 

Seed with `Instant::now().nanos()` or something like that, maybe.

**Comment by japaric** [comment]
> Uhm....

You should read through the Unsafe Code Guidelines team discussions. Apparently most `unsafe` operations are UB now. In any case, `mem::uninitialized` is going to be deprecated in favor of `MaybeUninit` and it's UB to read out its inner value if it has not been previously initialized.

**Comment by therealprof** [comment]
... and of course the Rng is seeded on each invocation of the random token function while the seed is only increasing each second which one fast machines means: crap (and I've been able to experience it first hand). I've added an atomic counter, increased on each invocation (much easier than the pro way of initialising once and reusing the same Rng), to continuously change the seed. Now collisions are a thing of the past.

File: macros/src/lib.rs [hunk 1]
```diff
@@ -6,10 +6,17 @@ extern crate rand;
 extern crate quote;
 extern crate proc_macro2;
 extern crate syn;
+extern crate core;
 
+use core::mem;
```
Comment (japaric) [inline macros/src/lib.rs]: Why `core::mem` and not `std::mem`?

File: macros/src/lib.rs [hunk 2]
```diff
@@ -492,7 +499,10 @@ pub fn pre_init(args: TokenStream, input: TokenStream) -> TokenStream {
 
 // Creates a random identifier
 fn random_ident() -> Ident {
-    let mut rng = rand::thread_rng();
+    let seed = SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_secs();
+    CALL_COUNT.fetch_add(1, Ordering::SeqCst);
```
Comment (japaric) [inline macros/src/lib.rs]: This returns the previous value. Why not use that instead of doing another atomic load?

File: macros/src/lib.rs [hunk 3]
```diff
@@ -492,7 +499,10 @@ pub fn pre_init(args: TokenStream, input: TokenStream) -> TokenStream {
...
+    let seed = [seed, CALL_COUNT.load(Ordering::SeqCst) as u64];
+    let mut rng = rand::rngs::SmallRng::from_seed( unsafe { mem::transmute(seed) } );
```
Comment (japaric) [inline macros/src/lib.rs]: Let's not use `unsafe` code here. There are methods to go from `u64` to `[u8; 8]` and vice versa that could be used here.

**Comment by adamgreig** [comment]
Could we use `.subsec_nanos()` instead of `.as_secs()` to avoid the issue? I'm not sure which systems have `std` but don't give nanosecond-level timers...

File: macros/src/lib.rs (hunk 3 above)
Comment (therealprof) [reply macros/src/lib.rs]: To the best of my knowledge only in nightly...
https://doc.rust-lang.org/nightly/std/primitive.u64.html#method.to_be_bytes

Of course I could do some bitmasking. ;)

**Comment by therealprof** [comment]
> Could we use .subsec_nanos() instead of .as_secs() to avoid the issue? I'm not sure which systems have std but don't give nanosecond-level timers...

Where did you dig that out? 😲
However that only yields a 32 bit value so that doesn't simplify things...

File: macros/src/lib.rs (hunk 3 above)
Comment (japaric) [reply macros/src/lib.rs]: > To the best of my knowledge only in nightly...

Still? I thought it was already stabilized. Perhaps I was thinking of `f32.to_bits`.

> Of course I could do some bitmasking. ;)

I would prefer that over unsafe code.

**Comment by adamgreig** [comment]
I was more thinking you could seed it once with that and then not worry about the counter. Though I guess you have to do the same twiddling to turn it into `[u8; 8]`.

**Comment by therealprof** [comment]
So... bit twiddling it is.

**Comment by korken89** [comment]
Great work!
